---
title: "ISSS 608 Project Proposal"
subtitle: "Movie Trend Analysis for Business Insights"
editor: visual
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    warning: false
    message: false
author:
  - name: "Shi Chee Liang"
    affiliations:
    - name: "Singapore Management University"
  - name: "Srivatsan Madapuzi Srinivasan"
    affiliations:
    - name: "Singapore Management University"
  - name: "Siddharth Singh"
    affiliations:
    - name: "Singapore Management University"
date: "12 February 2023"
date-modified: "`r Sys.Date()`"
---

## **Background**

The movie industry is constantly evolving, with new films being produced and released every year. To understand the current state of the industry and predict future trends, movie trend analysis is an essential tool. By analyzing various data sources such as box office performance, critical reception, and audience demographics, analysts can gain insights into the popularity of different genres, production techniques, and marketing strategies. This information can then be used by film studios, production companies, and investors to make informed decisions about future projects. Additionally, movie trend analysis can help movie theaters and streaming platforms plan their schedules and allocate resources to maximize their profits. With the increasing amount of data being generated in the movie industry, movie trend analysis has become an important tool for staying ahead of the curve and predicting the next big hit.

## **Motivation**

There are several motivations behind the development and use of movie trend analysis tools. These include:

1.  To Improve Decision-Making: Movie trend analysis provide valuable insights into the current state of the movie industry, helping individuals and organizations make informed decisions about future projects.

2.  To Identify Opportunities: By identifying trends and patterns in the data, movie trend analysis tools can help users identify new opportunities for success in the industry.

3.  To Maximize Profits: By understanding the success factors of different films and genres, movie trend analysis tools can help movie theaters, production companies, and investors maximize their profits.

## **Objectives**

Our project is interested in the following problems.

1.	To identify features of movies that are more popular in recent years. This can facilitate decision-making for companies that may be interested in investing in movie projects.

2.	To apply regression models in an attempt to predict the ROI of a particular movie project given various feature data, like genre, budget, etc.

3.	(stretch goal) to identify if the increasing popularity of Over-The-Top (OTT) services and implementation of COVID measures had impacted people's movie viewing habits, over the past 5 years

## **Data Set**

To analyze and plot the required graphs, these are the data set and their description that our team will be exploring:\
\
•   **movies.csv:** To retrieve all movie information like release year, box office revenue, etc.\
•   **OTTAppUsage.csv:** To retrieve all usage of various OTT platforms.\
•   **OTTRevenue.csv:** To retrieve revenue generated by OTT platforms.\
•   **OTTLibrarySize.csv:** To retrieve the size of OTT platforms' contents.\
•   **OTT_Titles.csv:** To retrieve all the titles in OTT platforms.
